### ISSUE TITLE
Support WES API

### ISSUE THREAD

**Issue by michael-kotliar** [CompEpigen/CWLab#19]
Hello,

Is there any way to use [WES API](https://github.com/ga4gh/workflow-execution-service-schemas) for submitting new jobs to the runner. Also, I'm wondering if your software provides any mechanisms for executing workflows on a multinode system or it should be managed by the executor itself.

Thanks

**Comment by KerstenBreuer** [comment]
Hi Michael,

you are definitely capable of doing so. When creating CWLab, a main concern was that people can integrate it into their specific software environment, no matter which setup they are using to execute CWL workflows. This is realized via execution profiles:

Essentially an execution profile is a bash script which is broken up into 4 steps:
`pre_exec`, `exec`, `eval`, and `post_exec`. Please have a look at the documentation: https://github.com/CompEpigen/CWLab#exec-profiles. All tree steps are executed via [pexpect ](https://pexpect.readthedocs.io/en/stable/api/pexpect.html) (python port of the expect library) in the same terminal sequentially. This means you can also switch into interactive python session or ssh to other machines just as you would do manually in a terminal. CWLab waits for completion of each step, checks the exit code and reports this to the web interface.

So you have ultimative freedom to configure the execution. I attached an example how to run CWL using [Toil](https://github.com/DataBiosphere/toil) on multinode systems (here lsf):

```
EXEC_PROFILES:
    toil_lsf_cluster:
        shell: bash
        max_retries: 2
        timeout:
            pre_exec: 120
            exec: 86400
            eval: 120
            post_exec: 120
        pre_exec: |
            source /path/to/venv/bin/activate # activate virtual env where toil is installed
            # create required temporary directories:
            JOBSTORE="${OUTPUT_DIR}/jobstore"
            TEMP_DIR="${OUTPUT_DIR}/temp"
            TEMP_OUT_DIR="${OUTPUT_DIR}/temp_out"
            WORK_DIR="${OUTPUT_DIR}/work"
            BASE_DIR="${OUTPUT_DIR}/base"
            mkdir -p \
                "${TEMP_DIR}" \
                "${TEMP_OUT_DIR}" \
                "${WORKDIR}" \
                "${BASEDIR}"
        exec: |
            cwltoil --batchSystem=lsf --disableCaching \
                --jobStore "${JOBSTORE}" \
                --tmp-outdir-prefix "${TEMP_OUT_DIR}" --tmpdir-prefix "${TEMP_DIR}" \
                --workDir "${WORK_DIR}" --basedir "${BASE_DIR}" --outdir "${OUTPUT_DIR}" \
                "${CWL}" "${RUN_YAML}" > "${LOG_FILE} 2>&1
        post_exec: |
            # clean up temporary directories:
            rm -rf \
                "${TEMP_DIR}" \
                "${TEMP_OUT_DIR}" \
                "${WORKDIR}" \
                "${BASEDIR}"
```

I have no experience with WES. However, in principle, you have to specify the following commands at the `exec` step:
(1) a command to submit the yaml file to the wes server
(2) a command which waits until the processing has been completed (alternatively you could also check for completion periodically and break the loop once the job has finished)

If you could provide me with a code snippet of how to achieve this, I could give you an example exec profile.

**Comment by michael-kotliar** [comment]
Hello, thank you for the response. Ah, I see, so your software basically works as a user interface for the workflow runner and both these parts should be installed on the same machine to be able to operate through the command line.  It would be also cool if it supported some kind of API to be able to use POST and GET for submitting and checking workflow execution status. And if this API is the same for all the workflow executors, you can easily connect to any of them.

**Comment by KerstenBreuer** [comment]
> Ah, I see, so your software basically works as a user interface for the workflow runner and both these parts should be installed on the same machine to be able to operate through the command line.

This is the simplest case, but you could definitely use the WES API to submit to a remote host. This is actually out plan, too. This could work via the WES CLI:   
1. submit a task: https://github.com/common-workflow-language/workflow-service#submit-a-workflow-to-run

2. then monitor until it completes: https://github.com/common-workflow-language/workflow-service#get-workflow-status

I will give an example as soon as I have hands on experience with WES.

However, we could also think of a direct integration via the python api of WES. Would you prefer this?

**Comment by KerstenBreuer** [comment]
> It would be also cool if it supported some kind of API to be able to use POST and GET for submitting and checking workflow execution status.   

This is in deed interesting. Technically it is already possible today, you just need to drop post requests with JSON metadata to the appropriate routes. E.g. the route "/generate_param_form_sheet/" (https://github.com/CompEpigen/CWLab/blob/master/cwlab/web_app/create_job.py#L77) followed by "/create_job/" (https://github.com/CompEpigen/CWLab/blob/master/cwlab/web_app/create_job.py#L327) to create a job and the route "/start_exec/" (https://github.com/CompEpigen/CWLab/blob/master/cwlab/web_app/job_exec.py#L141) to start execution.

However, one can still polish this experience. I will mark that as a future feature.
Thanks a lot

**Comment by KerstenBreuer** [comment]
A first draft is at https://github.com/CompEpigen/CWLab/tree/wes_integration/cwl2wes.

We will progress on this under #75
