### ISSUE TITLE
Use requirements.txt

### ISSUE THREAD

**Issue by MariusDieckmann** [CompEpigen/CWLab#36]
Use requirements.txt to install dependencies

**Comment by MariusDieckmann** [comment]
This should also make the install_dependencies scripts redundant.

**Comment by KerstenBreuer** [comment]
Hi Marius,
thanks a lot. The install_dependencies scripts are actually not in use anymore. I should have removed them a while ago.

Currently the dependencies are managed by pip and are declared in the `setup.py` (https://github.com/CompEpigen/CWLab/blob/master/setup.py#L26).

**Comment by KerstenBreuer** [comment]
Can you checkout commit: https://github.com/CompEpigen/CWLab/commit/d61406fcae455b52941830ebed06c5644f4e6999

I followed the recommendations in [this](https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py) discussion (post 35) and added a simple "." to the `requirements.txt`. This redirects pip to the setup.py when running `python3 -m pip install -r requirements.txt`.

The install_dependencies scripts were removed.

Would you agree with this solution?

**Comment by MariusDieckmann** [comment]
Thanks this would do the trick, too. Can be closed.
