### ISSUE TITLE
Add support for CommandInputEnumSchema 

### ISSUE THREAD

**Issue by KerstenBreuer** [CompEpigen/CWLab#39]
CWLab currently only supports standard [CWLTypes](https://www.commonwl.org/v1.1/CommandLineTool.html#CWLType). However, the CommandInputEnumSchema is also be very useful for GUI Users.

**Comment by KerstenBreuer** [comment]
Connected to #38

**Comment by KerstenBreuer** [comment]
Possible implementation of `symbols` array via an `<select>` field enabling a drop-down experience.

**Comment by KerstenBreuer** [comment]
@Athanaseus this feature is now present in the dev branch. Once #40 is resolved, I will merge everything to the master branch and make a new release.

**Comment by Athanaseus** [comment]
Thanks @KerstenBreuer
