### ISSUE TITLE
OIDC client access_token undefined after callback

### ISSUE THREAD

**Issue by KerstenBreuer** [CompEpigen/CWLab#70]
refers to branch https://github.com/CompEpigen/CWLab/tree/feature/oidcsupport:

OIDC client was used from [here](https://github.com/IdentityModel/oidc-client-js).

It is initiated [here](https://github.com/CompEpigen/CWLab/blob/feature/oidcsupport/cwlab/web_app/templates/main.html#L76) with the configs as defined [here](https://github.com/CompEpigen/CWLab/blob/feature/oidcsupport/docker/dev_elixir/config.yaml#L14-L21):
````
const oidcUserManager = useOIDC ? new Oidc.UserManager(oidcConf) : null
````
````
OIDC_CONF: {
  response_type: 'access_token',
  scope: 'openid profile email',
  authority: 'https://login.elixir-czech.org/oidc/',
  client_id: 'b1f68121-faec-4196-ab51-66eb61660ece',
  redirect_uri: 'https://cwlab-oidc.krini.ingress.rancher.computational.bio/loginoidc',
  post_logout_redirect_uri: 'https://cwlab-oidc.krini.ingress.rancher.computational.bio/'
}
````
The callback script can be found [here](https://github.com/CompEpigen/CWLab/blob/feature/oidcsupport/cwlab/web_app/templates/callback.html):
```<!DOCTYPE html>
<html lang="en">
    <head>
        <script src="/static/oidc-client.min.js"></script>
        <script>
            window.onload = function () {
                let oidcConf = JSON.parse('{{ config.OIDC_CONF | tojson | safe }}')
                oidcConf["response_mode"] = "query"
                new Oidc.UserManager(oidcConf).signinRedirectCallback().then(function() {
                    window.location = "{{ url_for('main') }}"
                }).catch(function (e) {
                    console.log(e);
                    document.getElementById('error_explanation').innerText = "Problem has occured";
                    document.getElementById('error_place').innerText = e;
                });   
            }
        </script>
    </head>
</html>
```

When we try to get the access token via `const user = await oidcUserManager.getUser()`, the access_token field of the user object is undefined. No error are thrown.

**Comment by dBucik** [comment]
Please change the configuration option **response_type** to value **token** or **token id_token**
That should fix the issue.

**Comment by KerstenBreuer** [comment]
Has been resolved, thanks to @dBucik
