### ISSUE TITLE
Can't see any runs in the Job execution panel

### ISSUE THREAD

**Issue by illusional** [CompEpigen/CWLab#9]
Hi! Trying out CWLab with a simple untar / compile / tar example. I've packed the workflow and validated it still works with CWLTool. I'm able to import my workflow (attached as `simple-packed.cwl` in the zip below, and I create a new Job (both single and multi run), but when I go to the _Job Execution & Results_ panel, I can see the jobs but no runs (see screenshot).

![image](https://user-images.githubusercontent.com/22381693/62087928-da66db80-b2a6-11e9-912d-72e8a5b536d2.png)

Using version: `0.1.1` with no config, the default configuration and a `Debug: True` config.

Attachment: [wf.zip](https://github.com/CompEpigen/CWLab/files/3444492/wf.zip)

- `simple-packed.cwl` - The containerized workflow to run`
- `hello.tar`, the workflow input (contains a Hello.java file that never gets executed).

Edit: I didn't get any debug information and there's nothing in the sqlite db (`~/cwlab/database/cwlab.db`).

**Comment by KerstenBreuer** [comment]
Hi, thanks a lot for trying the early release and for sharing this detailed issue. 

I could reproduce it and identified the bug. I will push a fix to the master branch, soon.
Thanks

**Comment by KerstenBreuer** [comment]
I have released some fixes to the master branch. If you have time, could you please review them and tell me whether your issue is resolved? You can use the ``cwlab.py`` script as alternative entry point (`./cwlab.py up --config my_config.yaml`).

Thanks a lot

**Comment by illusional** [comment]
Awesome! It executed and it notified me that it collected the results. I can't see any details when I click the eye (details) button, but looks like that's [coming soon](https://github.com/CompEpigen/CWLab#job-execution) :)

**Comment by KerstenBreuer** [comment]
Yeah, exactly. The details button is not implemented yet. But the output should be in the exec dir.

Thanks a lot for trying it out.
